### ISSUE TITLE
[Suggestion] Add a more visible search bar (including on the home page)

### ISSUE THREAD

**Issue by Romitou** [Olyno/skript-website#10]
Hi, I suggest adding a more visible search bar on the home page to save time when looking for a particular syntax. I am also proposing to add it to the home page in addition to the documentation pages. 😉

**Comment by Olyno** [comment]
Hi,
Thanks for your suggestion.

> I suggest adding a more visible search bar on the home page to save time when looking for a particular syntax.

Which "search bar on the home page" is it? There are no search bar on the home page. Can you make a screenshot to show me which search bar are you talking about please?
